### ISSUE TITLE
says I'm an admin when I'm a collab

### ISSUE THREAD

**Issue by jdx** [heroku/heroku-orgs#43]
```
$ heroku members:remove jeff@heroku.com -o addons-ux
Removing jeff@heroku.com from addons-ux... !!!
 ▸    Your role admin on the organization addons-ux is not allowed to perform that action.
```

```
$ heroku orgs
heroku orgs
addons-ux                   collaborator
ex-idfed-sfdc-idp           collaborator
heroku                      admin
heroku-add-ons              admin
heroku-business-operations  collaborator
heroku-marketing            collaborator
heroku-support              collaborator
```

**Comment by raulb** [comment]
@dickeyxxx that error (`Your role admin on the organization addons-ux is not allowed to perform that action.`) is returned automatically by API. It might be an error caused by the fact that `addons-ux` is an org with static permissions.

Is that possible? @naaman @eablack @kahlouie

**Comment by jdx** [comment]
it happened for me on any app I was a collab on

**Comment by jdx** [comment]
though yeah, it probably is the API. In hindsight I'm not sure why I put the issue here.

**Comment by raulb** [comment]
@dickeyxxx no worries. Thanks for catching this up.

Tracking here: https://github.com/heroku/api/issues/5887.
