### ISSUE TITLE
-r flag doesn't work

### ISSUE THREAD

**Issue by kahlouie** [heroku/heroku-orgs#45]
```
heroku members:set email@email.com -r admin -o ORG-NAME
 ▸    Required flag:  -r, --role ROLE
```

also doesn't work if you user `heroku members:set email@email.com -o ORG-NAME -r admin`

**Comment by kahlouie** [comment]
also, --role does work

**Comment by raulb** [comment]
@kahlouie thanks. I'll investigate

**Comment by raulb** [comment]
@kahlouie Can you confirm you're using the latest version of `heroku-orgs`?

I don't seem to be able to reproduce it.

```
$ heroku version | grep heroku-orgs
heroku-orgs@1.1.0
```

Also, just to make sure you're not using a linked version, can you run `heroku plugins:uninstall heroku-orgs` and run it again?

**Comment by kahlouie** [comment]
Seems to be working again, I can't reproduce again either.

**Comment by sclasen** [comment]
--role and --remote clash on older versions, sounds like its fixed
tho..nice!
