### ISSUE TITLE
port these commands to this plugin

### ISSUE THREAD

**Issue by jdx** [heroku/heroku-orgs#6]
- [x] apps:join
- [x] apps:leave
- [x] apps:lock
- [x] apps:unlock
- [x] members
- [x] members:add
- [x] members:remove
- [x] members:set
- [x] orgs
- [x] orgs:open

~~\- [[ ] orgs:info :question:](https://github.com/heroku/heroku-sudo/blob/master/commands/orgs/info.js)~~
- [x] sharing
- [x] sharing:add
- [x] sharing:remove
- [x] sharing:transfer

**Comment by jdx** [comment]
@raulb alright these are done minus the sharing commands that I think we can leave out since access does the same thing

**Comment by raulb** [comment]
@dickeyxxx OMG :metal: !!!

![](https://s3.amazonaws.com/f.cl.ly/items/1V1l2y1e3I1o1M3F0x2G/beats.gif)

Will check them out!,Thanks!!!
- [x] [apps:transfer](https://github.com/heroku/heroku-orgs/pull/13)
- [x] [apps:*](https://github.com/heroku/heroku-orgs/pull/11)
- [x] [members:*](https://github.com/heroku/heroku-orgs/pull/12)
- [x] [orgs:*](https://github.com/heroku/heroku-orgs/pull/8)

**Comment by raulb** [comment]
@dickeyxxx what I'll do with those `sharing:*` is creating an alias, as we talked earlier today.
