### ISSUE TITLE
members:set is broken

### ISSUE THREAD

**Issue by msakrejda** [heroku/heroku-orgs#83]
```
maciek@mothra:~$ heroku members:set --role admin aquint@heroku.com --org dod
Inviting aquint@heroku.com to dod as admin... !
 ▸    aquint@heroku.com user cannot be invited because they are already in dod team
```
It looks like there was an API change that means you can't "upsert" roles anymore, which seems to be the behavior that `members:set` was relying on (since it's just a copy of `members:add`).

**Comment by msakrejda** [comment]
For what it's worth, I worked around this by changing permissions via Dashboard, which worked fine.

**Comment by nsamsami** [comment]
Per Raul, original intention was to change role similar to what you can do in the Dashboard. 

members: set should be to update the role after the fact

members: add should enable you to create member AND set their role 

Ike not sure why role change got conflated with inviting people to the team. Devex suggests we talk to core services

**Comment by jdx** [comment]
Proposed solution: Catch the error the invite gives and call members:set if it's the already invited error
